name: QMK build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-qmk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Setup QMK
        run: |
          pip install qmk
          ./util/qmk_install.sh -y
          qmk setup -H ./

      - name: Compile firmware
        run: |
          qmk config user.keyboard=crkbd/rev4_1/standard user.keymap=luckasranarison
          qmk generate-compilation-database
          qmk compile --compiledb

      - uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: firmware
          path: .build
